name: Build and publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.0
        with:
          nsis-version: 3.08
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: ./dist/GreenAcidPipe ${{ github.action_ref }} Setup.exe
  draft-release:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

    steps:
      - name: Draft new release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
  upload-binary:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: ["draft-release", "build"]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: ${{ matrix.platform }}
          path: ./installer.exe
      - name: Upload release asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.draft-release.outputs.upload_url }}
          asset_path: ./installer.exe
          asset_name: GreenAcidPipe ${{ github.action_ref }} Setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
