name: Build and publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install NSIS
        uses: repolevedavaj/install-nsis@v1.0.0
        with:
          nsis-version: 3.08
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 18.x
      - name: Setup appid.json
        run: echo "{`"clientId`":`"$Env:GAP_CLIENT_ID`"}" > appid.json
        env:
          GAP_CLIENT_ID: ${{ secrets.GAP_CLIENT_ID }}
      - run: yarn install
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: ./dist/GreenAcidPipe ${{ github.ref_name }} Setup.exe
  draft-release:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}

    steps:
      - name: Draft new release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
  upload-binary:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: ["draft-release", "build"]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: artifact
          path: ./installer.exe
      - run: tree
      - name: Upload release asset
        uses: tanyagray/upload-release-asset@v1.1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.draft-release.outputs.upload_url }}
          asset_path: ./installer.exe
          asset_name: GreenAcidPipe ${{ github.ref_name }} Setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
